server.port=${PORT:8080}
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Cloudinary — untuk lokal pakai nilai default setelah titik dua
# Untuk Railway, akan dibaca dari Environment Variables
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:spwwtr9q}
cloudinary.api-key=${CLOUDINARY_API_KEY:142937736777427}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:nhD96oDFgo1JXU1qCzkaWU_2Gjs}